# Generated by Django 4.0.5 on 2022-07-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_remove_book_author_author_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='FilmDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('films', models.ManyToManyField(to='api_app.film')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=64, null=True)),
                ('format', models.CharField(choices=[('unknown', 'Unknown'), ('cd', 'CD'), ('vinyl', 'Vinyl')], default='unknown', max_length=10)),
                ('composer', models.ForeignKey(on_delete=models.SET('MISSING'), related_name='composer', to='api_app.artist')),
                ('performer', models.ForeignKey(on_delete=models.SET('MISSING'), related_name='performer', to='api_app.artist')),
            ],
            options={
                'ordering': ['performer'],
            },
        ),
    ]
