# Generated by Django 4.0.5 on 2022-07-04 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_artist_film_alter_book_options_filmdirector_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composer', to='api_app.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performer', to='api_app.artist'),
        ),
    ]
