# Generated by Django 4.0.5 on 2022-07-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_alter_album_composer_alter_album_performer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='Autor', max_length=128),
            preserve_default=False,
        ),
    ]
