# Generated by Django 4.0.5 on 2022-07-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_remove_author_first_name_remove_author_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmdirector',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='filmdirector',
            name='last_name',
        ),
    ]
